### ISSUE TITLE
Script.py throwing access_token error.

### ISSUE THREAD

**Issue by abhinavkumar10** [microsoftgraph/security-api-solutions#109]
Script.py throwing access_token error

access_token error encountered when running script.py after following the steps and making required changes in the config.py file like adding access token and client secret. The script.py encounters error in RequestManager.py 

Traceback (most recent call last):
  File "script.py", line 100, in <module>
    main()
  File "script.py", line 93, in main
    with RequestManager(total_indicators) as request_manager:
  File "/home/srvadmin/mispToSentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 42, in __enter__
    access_token = self._get_access_token(
  File "/home/srvadmin/mispToSentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 71, in _get_access_token
    access_token = requests.post(
KeyError: 'access_token'

Regenerated app registration as-well in order to validate if error was related to client id and secret. Gives same result. 

![image](https://user-images.githubusercontent.com/55996511/153272682-32f0274a-45b7-415e-86dc-84b9ee316df5.png)

**Comment by realzacharycheng** [comment]
Hi, it seems like you have solution for this error. Any suggestion to solve this error ? Thanks
