### ISSUE TITLE
Script.py throwing access_token error

### ISSUE THREAD

**Issue by abhinavkumar10** [microsoftgraph/security-api-solutions#110]
Script.py throwing access_token error

access_token error encountered when running script.py after following the steps and making required changes in the config.py file like adding access token and client secret. The script.py encounters error in RequestManager.py

Traceback (most recent call last):
File "script.py", line 100, in
main()
File "script.py", line 93, in main
with RequestManager(total_indicators) as request_manager:
File "/home/srvadmin/mispToSentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 42, in enter
access_token = self._get_access_token(
File "/home/srvadmin/mispToSentinel/security-api-solutions/Samples/MISP/RequestManager.py", line 71, in _get_access_token
access_token = requests.post(
KeyError: 'access_token'

Regenerated app registration as-well in order to validate if error was related to client id and secret. Gives same result.

![153273482-d7f33bf7-f408-4430-a761-196aefb2583f](https://user-images.githubusercontent.com/55996511/153276393-fb1f315c-474d-430a-8e20-3c840dc681b5.png)

**Comment by realzacharycheng** [comment]
Hi, I am having the same issue. Do you find any solution yet? Thanks.

**Comment by albchen** [comment]
I had this issue at first. Make sure the secret being sent in the request is the client secret **value**, not the client secret ID. Also, it's worth testing your post request separately to see if there is a successful response. Invalid responses do not return an access_token json object.
