### ISSUE TITLE
MDATP - UnboundLocalError: local variable 'response' referenced before assignment Error

### ISSUE THREAD

**Issue by cneitaGit** [microsoftgraph/security-api-solutions#50]
# UnboundLocalError: local variable 'response' referenced before assignment

# General
Script seems to run seamlessly pulling the IOCs from the MISP and pushing them to MDAPT but hits the following error on the last IOC each and every time:

"Traceback (most recent call last):
  File "script.py", line 96, in main
    request_manager.handle_indicator(request_body)
  File "/home/*/*/MISP/RequestManager.py", line 199, in handle_indicator
    self._post_one_to_graph()
  File "/home/*/*/Samples/MISP/RequestManager.py", line 178, in _post_one_to_graph
    self._log_post(response)
  File "/home/*/*/Samples/MISP/RequestManager.py", line 98, in _log_post
    if len(response['value']) > 0:
KeyError: 'value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 100, in <module>
    main()
  File "script.py", line 96, in main
    request_manager.handle_indicator(request_body)
  File "/home/*/*/Samples/MISP/RequestManager.py", line 137, in __exit__
    self._post_one_to_graph()
  File "/home/*/*/Samples/MISP/RequestManager.py", line 178, in _post_one_to_graph
    self._log_post(response)
UnboundLocalError: local variable 'response' referenced before assignment "

After receiving this error the script immediately stops

**Comment by chinguyen1** [comment]
@cneitaGit Thank you for the feedback! We are looking into the issue and will provide update on the fix here.

**Comment by chinguyen1** [comment]
@cneitaGit The bug has been resolved. Please git pull the repo and give it another try. Let us know if you still run into any issues or have any questions.

**Comment by chinguyen1** [comment]
@cneitaGit Has the updated script worked for you as expected?

**Comment by chinguyen1** [comment]
Closing this as it's related to issue [#52](https://github.com/microsoftgraph/security-api-solutions/issues/52)
